RULES = [
    {
        "column": "A",
        "label": "CÓDIGO",
        "name": "code",
        "rules": "nullable",
    },
    {
        "column": "B",
        "label": "NOME",
        "name": "name",
        "rules": "required|string|max:50",
    },
    {
        "column": "C",
        "label": "CPF",
        "name": "cpf",
        "rules": "nullable|unique|digits:11",
    },
    {
        "column": "D",
        "label": "RG",
        "name": "rg",
        "rules": "nullable|string|max:20",
    },
    {
        "column": "E",
        "label": "CNPJ",
        "name": "cnpj",
        "rules": "nullable|unique|digits:14",
    },
    {
        "column": "F",
        "label": "IE",
        "name": "ie",
        "rules": "nullable|string|max:20",
    },
    {
        "column": "G",
        "label": "INDICADOR ICMS",
        "name": "icms_indicator",
        "rules": "nullable|enum:1,2,9",
    },
    {
        "column": "H",
        "label": "TELEFONE",
        "name": "phone",
        "rules": "nullable|digits_between:10,11",
    },
    {
        "column": "I",
        "label": "WHATSAPP",
        "name": "whatsapp",
        "rules": "nullable|digits_between:10,11",
    },
    {
        "column": "J",
        "label": "EMAIL",
        "name": "email",
        "rules": "nullable|email|max:50",
    },
    {
        "column": "K",
        "label": "LIMITE DE CRÉDITO",
        "name": "credit_limit",
        "rules": "nullable|numeric|min:0|max:999999.99",
    },
    {
        "column": "L",
        "label": "ATIVO",
        "name": "active",
        "rules": "nullable|boolean|enum:1,0,Y,N,S,NÃO,SIM,NAO",
    },
    {
        "column": "M",
        "label": "NOME DA MÃE",
        "name": "mother_name",
        "rules": "nullable|string|max:50",
    },
    {
        "column": "N",
        "label": "OBSERVAÇÕES",
        "name": "observations",
        "rules": "nullable|string|max:500",
    },
    {
        "column": "O",
        "label": "DATA DE NASCIMENTO",
        "name": "birth_date",
        "rules": "nullable|date|before_or_equal:today",
    },
    {
        "column": "P",
        "label": "ENDEREÇO",
        "name": "address",
        "rules": "nullable|string|max:50",
    },
    {
        "column": "Q",
        "label": "NÚMERO",
        "name": "number",
        "rules": "nullable|string|max:10",
    },
    {
        "column": "R",
        "label": "COMPLEMENTO",
        "name": "complement",
        "rules": "nullable|string|max:50",
    },
    {
        "column": "S",
        "label": "BAIRRO",
        "name": "neighborhood",
        "rules": "nullable|string|max:50",
    },
    {
        "column": "T",
        "label": "CIDADE",
        "name": "city",
        "rules": "nullable|string|max:50",
    },
    {
        "column": "U",
        "label": "ESTADO",
        "name": "state",
        "rules": "nullable|string|max:2",
    },
    {
        "column": "V",
        "label": "CEP",
        "name": "zip_code",
        "rules": "nullable|digits:8",
    },
]